Starfinder Enhanced Themes
foundryvtt-starfinder/foundryvtt-starfinder pull request #1319
Opened 2024-06-24 23:57 UTC by PaoloTorregroza

- [ ] Personal Trainer
- [X] Bouncer
- [X] Paranormal Investigator (Enhanced)
- [X] Pickpocket
- [X] Rancher
- [X] Starwalker (Enhanced)
- [X] Street Magician 
- [X] Vidgamer

2024-07-31 17:11 UTC, LebombJames requested changes

2024-07-31 17:11 UTC, LebombJames commented on src/items/themes/bouncer.json
> +      "value": "<p>From the vibrant nightlife of Absalom Station to the glitzy casinos of the Burning Archipelago, there are places throughout the galaxy where people gather to party and relax. But y
Some HTML tags in these themes have errant classes from copying from AoN (E.g `h2 ckass="title"`) which should be removed. Running cook should remove most of these.

2024-08-21 14:27 UTC, ian612 commented
This is duplicated here:
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/1377

2025-05-15 19:09 UTC, ian612 commented
A different version of this data was merged in #1377 , so going to close this PR.

2025-05-15 19:09 UTC, closed without merging