Roll Deprecated
foundryvtt-starfinder/foundryvtt-starfinder pull request #1389
Opened 2024-09-11 00:58 UTC by danimrath

roll has been deprecated in favor of rolls when doing ChatMessage.Create.

2024-12-17 13:24 UTC, ian612 commented
I tested it a bit and it seems to respect the roll visibility setting in the sidebar, but not the one selected in the popup dialog box. There might be something in the dialog application that needs to be tweaked as well?

![image](https://github.com/user-attachments/assets/792a78f2-be5e-4f72-b6c6-7f442a78bd07)

2024-12-17 13:33 UTC, ian612 requested changes
Fixes the sidebar setting for rolls, but dialog box roll visibility setting still seems to be ignored

2024-12-17 14:30 UTC, danimrath commented
> Fixes the sidebar setting for rolls, but dialog box roll visibility setting still seems to be ignored

Interesting. I wasn't actually trying to fix that specifically. I was fixing dice so nice and things trying to use the IsRoll flag. If you think that is related I can take a look later today though.

2024-12-17 14:41 UTC, ian612 commented
Ah woops, yep you're right the issue is different, so we should do a separate fix for what I was noticing. I'll test this out again later today and just verify the Dice So Nice functionality

2024-12-19 02:14 UTC, ian612 approved these changes
After testing, I see no issues and I think this is good to merge whenever you're ready to!

2024-12-19 04:43 UTC, merged