Roll Code Cleanup
foundryvtt-starfinder/foundryvtt-starfinder pull request #1395
Opened 2024-10-11 18:56 UTC by levirak

My intent with these changes is to simplify the code as much as I could with the goal of making the code easier for contributors to reason about and without changing its behavior.

I have divided this PR into several initiatives, each represented by a commit. The hope is that each commit should be thematically consistent to make review easier.

The biggest change was unifying the `skipUI` true/false paths to reduce code duplication. The consequence is that the `skipUI` flag now _only_ skips displaying the UI to the user, then carries on with some inferred default values.

One additional change I would like to make is to unify the "partless/partfull" paths, which fork at the `if (enabledParts?.length > 0)` statement. I have a few options I'm considering, but none I'm sufficiently pleased with. If that changes before this PR gets merged, I intend to update this PR with that change.

2024-10-13 04:09 UTC, danimrath commented
Tip of the hat to you for giving this a go. I haven't taken too close a look at the code but I loaded it up on my machine and the rolls/modifiers I double checked seemed fine.

2024-10-15 21:32 UTC, levirak commented
As a heads up, I've force pushed over my previous branch. My previous job got me into the habit of rewriting history quite aggressively. I'm trying to structure the commits to help in reviewing this CR, so when I revisited previous changes I rewrote the old commit rather than make new ones. If I start to see a bunch of code review activity I'll be more cautious with rebasing my branch.

This time the major change was removing the `<damageSection>` string from the roll code. I was careful to ensure that it caused no behavioral changes, but it is by far the _diciest_ (eh? eh?) change I've attempted so far. The solution I pushed today is quite conservative compared to some of the other solutions I threw out after they caused too much to blow up on me. For example, one line of development caused me to totally break situational modifiers for damage rolls because I hadn't been aware of the magic that is `@additional.modifiers.bonus`.

2024-10-21 03:46 UTC, danimrath commented
Hey, I tried loading up your latest PR and it is a breaking change. 
[localhost-1729482331197.log](https://github.com/user-attachments/files/17454721/localhost-1729482331197.log)
[localhost-1729482300881.log](https://github.com/user-attachments/files/17454722/localhost-1729482300881.log)

2024-10-21 03:57 UTC, levirak commented
Oh. Oops. Thanks for checking! I caught this myself the other day, but I guess I forgot to push those changes. It was a pretty silly mistake, too.

2024-10-22 16:25 UTC, ian612 commented
Just wanted to say thanks for taking a stab at this! My understanding is it's been a pain point for quite a while now and in need of a cleanup.

2024-10-22 17:15 UTC, levirak commented
Thanks for the encouragement. We'll see if I can be of any help. I'm still wrapping my head around the whole system, so for the moment I'm sticking to changes that have a minimal impact on actual behavior. Things like unifying duplicate code paths or simplifying data and control flow. My general guiding principal has been to iron out anything that surprises me along the way. Ideally the outcome of this PR is a code structure for the present implementation that's easier for contributors to reason about.

I've got some aspirations on my to-do list that I would instead do in different PRs. One is that, I'd like to change how parts / damage sections / damage groups work, such that they stop being special cases that change how you have to interact with `RollTree` and below. Another is that I'd like to evaluate alternatives to `@additional.modifiers.bonus`, which is a clever way to to get the UI to suggest known modifiers, but which I suspect is largely responsible for the existence of `RollTree` and `RollNode` at all.

2024-10-26 05:02 UTC, danimrath commented
Operatives Edge causes a NaN failure. You can use Iseph L8 from the compendium to test.

2024-10-26 16:25 UTC, levirak commented
Oh. It happens that my test character didn't have an init modifier that more complicated than a flat bonus, and `Number("1+1")` is a NaN. I'll have to add that case to my list.

2024-10-26 23:06 UTC, levirak commented
I noticed today that way back when I changed `buildRoll` to stop taking a callback, I also broke how items' max uses were calculated. Probably other things too, but that's what I noticed. It was a consequence of `buildRoll` being async, but the rules/engine code is synchronous (at least how I found it). Refactoring `buildRoll` to be a static method was a good opportunity to create a `buildRollSync` method that the rules closure could use.

2025-02-13 02:56 UTC, ian612 commented
Since this is pretty important code in the system, I'm going to try to test as many combinations of rolls as I can as part of the review. I'll list them in this comment and tick the boxes as I work my way through them

PC
 - [ ] Initiative
 - [ ] Saving Throw
 - [ ] Skill Check (1 Rank with Class)
 - [ ] Skill Check (1 Rank)
 - [ ] Skill Check (0 Ranks)
 - [ ] Ability Check
 - [ ] Weapon Attack (Proficient)
 - [ ] Weapon Attack (Not Proficient)
 - [ ] Weapon Attack (With Harrying Fire modifier)
 - [ ] Weapon Attack (with modifier on item)
 - [ ] Weapon Attack (with modifier on nested item, apply to parent container)
 - [ ] Weapon Damage
 - [ ] Weapon Damage (with modifier)
 - [ ] Feature Item Activation (click activate button)
 - [ ] Feature Item Roll (click icon)
 - [ ] Feature Item Damage (click button)
 - [ ] Spell Item Activation (click activate button)
 - [ ] Spell Item Roll (click icon)
 - [ ] Spell Item Attack
 - [ ] Spill Item Damage
 
 Chat Card
 - [ ] Attack
 - [ ] Damage
 - [ ] Save
 - [ ] Other Formula
 
 NPC
 - [ ] Initiative
 - [ ] Saving Throw
 - [ ] Skill Check (1 Rank with Class)
 - [ ] Skill Check (1 Rank)
 - [ ] Skill Check (0 Ranks)
 - [ ] Ability Check
 - [ ] Weapon Attack (Proficient)
 - [ ] Weapon Attack (Not Proficient)
 - [ ] Weapon Attack (With Harrying Fire modifier)
 - [ ] Weapon Attack (with modifier on item)
 - [ ] Weapon Attack (with modifier on nested item, apply to parent container)
 - [ ] Weapon Damage
 - [ ] Weapon Damage (with modifier)
 - [ ] Feature Item Activation (click activate button)
 - [ ] Feature Item Roll (click icon)
 - [ ] Feature Item Damage (click button)
 - [ ] Spell Item Activation (click activate button)
 - [ ] Spell Item Roll (click icon)
 - [ ] Spell Item Attack
 - [ ] Spill Item Damage
 
 Drone
 - [ ] Initiative
 - [ ] Weapon Attack
 - [ ] Weapon Damage
 - [ ] Feature Activation
 - [ ] Feature Roll
 
 Starship (PC Crew)
 - [ ] Piloting Check (initiative)
 - [ ] Piloting Check (with modifier)
 - [ ] Attack Roll (gunnery)
 - [ ] Attack Roll (with modifier)
 - [ ] Stunt
 - [ ] Stunt (with modifier)
 - [ ] Other crew action (demand)
 - [ ] Other crew action (demand, with modifier)
 - [ ] Other crew action (demand, with Life Support damage)
 
 Starship (NPC Crew)
 - [ ] Piloting Check (initiative)
 - [ ] Attack Roll (gunnery)
 - [ ] Stunt
 - [ ] Other crew action (demand)
 - [ ] Other crew action (demand, with Life Support damage)
 
 Journal
 - [ ] Inline Skill Check

2025-02-13 06:46 UTC, ian612 commented
I've checked through all the rolls above and haven't been able to find any where issues pop up. I'll try to do a more detailed look through the code soon, and hopefully get this merged

2025-02-19 14:32 UTC, ian612 commented
I've found another issue that will need to be resolved with the roll simplification. In the below image you can see the damage roll from the Entropic Strike of the Iconic Velloro (level 8) in system version 27.1 as an example.

![image](https://github.com/user-attachments/assets/80318e19-cb1c-4249-a1ba-e2f77d5c09a4)

The roll formulas for these damage sections are:
1. `(lookupRange(@classes.vanguard.levels, 0, 1, 1, 6, 2, 9, 3, 12, 4, 13, 5, 14, 6, 15, 7, 16, 8, 17, 9, 18, 10, 19, 11, 20, 12))d(lookupRange(@classes.vanguard.levels, 0, 1, 3, 3, 4, 5, 6)) + @abilities.con.mod + (lookupRange(@classes.vanguard.levels, 0, 10, @abilities.str.mod) + (lookupRange(@classes.vanguard.levels, 0, 3, ceil(@classes.vanguard.levels / 2))))`
2. `(lookupRange(@item.level, 0, 1, 1, 6, 2, 9, 3, 12, 4, 13, 5, 14, 6, 15, 7, 16, 8, 17, 9, 18, 10, 19, 11, 20, 12))d(lookupRange(@item.level, 0, 1, 3, 3, 4, 5, 6)) + @abilities.con.mod + (lookupRange(@classes.vanguard.levels, 0, 10, @abilities.str.mod))`

As you can see, these complex formulas should get simplified down in the chat card to make it easier to see what's happening. In this branch, however, it looks like that simplification is getting skipped.

![image](https://github.com/user-attachments/assets/86aff8c7-af5a-4596-9427-4877c4a66672)

2025-02-19 14:33 UTC, ian612 requested changes
See issue with roll formula simplification in above comment ^^

2025-02-19 17:55 UTC, levirak commented
ah. Something about that may have changed since I started writing this PR. I don't recall `lookupRange` simplifying down to one number last time I played a SF1e game. I'll look into this.

Hey. Speaking of Vanguard's Entropic Strike, I don't believe that is calculated correctly. If I splay that formula out and simplify a little it looks like this:

```
(lookupRange(@classes.vanguard.levels, ...))d(lookupRange(@classes.vanguard.levels, ...))
+ @abilities.con.mod
+ lookupRange(@classes.vanguard.levels, 0, 10, @abilities.str.mod)
+ lookupRange(@classes.vanguard.levels, 0, 3, ceil(@classes.vanguard.levels / 2))
```

That last addition comes from Vanguard's Weapon Specialization at level 3, which reads:

> You also gain a special form of weapon specialization for your entropic strike, allowing you to add a bonus to your damage equal to your vanguard class level plus half of any other class levels you have.

In addition, I'm not sure why ceil is used, as the standard assumption is to round down. I think the right way to calculate the Weapon Specialization would be:

```
@classes.vanguard.levels + floor((@details.level.value - @classes.vanguard.levels) / 2)
```

Or the shorter but less clear equivalent: `floor((@classes.vanguard.levels + @details.level.value) / 2)`

2025-02-19 21:06 UTC, levirak commented
I commented too quickly, and I hadn't noticed that the Weapon Specialization Vanguard feature mixes in in a way that complicates things. It does so because (from the rules) "Your entropic strike is a magical one-handed advanced melee weapon with the operative weapon special property". The full roll ends up looking like this:

```
(lookupRange(@classes.vanguard.levels, ...))d(lookupRange(@classes.vanguard.levels, ...))
+ @abilities.con.mod
+ lookupRange(@classes.vanguard.levels, 0, 10, @abilities.str.mod)
+ lookupRange(@classes.vanguard.levels, 0, 3, ceil(@classes.vanguard.levels / 2))
+ @details.level.value[Weapon Specialization Vanguard]
- ceil(@details.level.value / 2)[Weapon Specialization Vanguard]
```

I'll spare you the details, but by my analysis of the Weapon Specialization part ended up looking like this:

```
if @classes.vanguard.levels is even OR @classes.vanguard.levels is even:
    bonus is @classes.vanguard.levels + floor(@classes.not-vanguard.levels/2)
else @classes.vanguard.levels is odd AND @classes.vanguard.levels is odd:
    bonus is @classes.vanguard.levels + (@classes.not-vanguard.levels+1)/2
```

It looks like there are off-by-one errors when a player has an odd number of vanguard and non-vanguard levels. To validate that, I wrote a quick script and produced the following table. Total character level is across the side, number of non-vanguard class levels is across the top, and each cell is `<current value>/<correct value>`. I designed the table to only show characters with at least 3 vanguard levels, as everything else is irrelevant. I also spot checked these results in Foundry, and they appear correct.

||0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|
|--:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|3|3/3||||||||||||||||
|4|4/4|4/3|||||||||||||||
|5|5/5|4/4|4/4||||||||||||||
|6|6/6|6/5|5/5|5/4|||||||||||||
|7|7/7|6/6|6/6|5/5|5/5||||||||||||
|8|8/8|8/7|7/7|7/6|6/6|6/5|||||||||||
|9|9/9|8/8|8/8|7/7|7/7|6/6|6/6||||||||||
|10|10/10|10/9|9/9|9/8|8/8|8/7|7/7|7/6|||||||||
|11|11/11|10/10|10/10|9/9|9/9|8/8|8/8|7/7|7/7||||||||
|12|12/12|12/11|11/11|11/10|10/10|10/9|9/9|9/8|8/8|8/7|||||||
|13|13/13|12/12|12/12|11/11|11/11|10/10|10/10|9/9|9/9|8/8|8/8||||||
|14|14/14|14/13|13/13|13/12|12/12|12/11|11/11|11/10|10/10|10/9|9/9|9/8|||||
|15|15/15|14/14|14/14|13/13|13/13|12/12|12/12|11/11|11/11|10/10|10/10|9/9|9/9||||
|16|16/16|16/15|15/15|15/14|14/14|14/13|13/13|13/12|12/12|12/11|11/11|11/10|10/10|10/9|||
|17|17/17|16/16|16/16|15/15|15/15|14/14|14/14|13/13|13/13|12/12|12/12|11/11|11/11|10/10|10/10||
|18|18/18|18/17|17/17|17/16|16/16|16/15|15/15|15/14|14/14|14/13|13/13|13/12|12/12|12/11|11/11|11/10|
|19|19/19|18/18|18/18|17/17|17/17|16/16|16/16|15/15|15/15|14/14|14/14|13/13|13/13|12/12|12/12|11/11|11/11|
|20|20/20|20/19|19/19|19/18|18/18|18/17|17/17|17/16|16/16|16/15|15/15|15/14|14/14|14/13|13/13|13/12|12/12|12/11|

How to solve this is much less clear.

2025-02-19 23:21 UTC, levirak commented
As for the actual problem with roll simplification, my easiest solution is to revert b35c4bdb0. I'm still not a fan of the original implementation, and I suspect it's harboring some latent bugs. My main issue is that some semantic / inspection information is getting lost in the simplification. For example, the contributions of Con and Weapon Specialization get added together for Entropic Strike, when I'd rather they stay separate. If my GM asks "why do you get a plus 10?", rather than shrug and say SFRPG told me so, I'd like to see an itemized breakdown when I inspect the roll.

Actually implementing that is a different story, because yeah, `lookupRange` hinders rather that helps that aim. The best "correct" solution that comes to mind involves modifying an AST, but I'm not sure that's possible / supported / desirable. I may look into it, but after a quick inspection it seems like that would be a rather involved process which goes a bit beyond the stated aim of this PR, which is primarily refactoring.

2025-02-22 01:08 UTC, ian612 commented
Thanks for spotting and recording the Vanguard-specific issue. Weapon Specialization is something that I feel could be implemented better than the current method, in a more bespoke manner since it's so core to all the classes.

BUT back to this PR, which is just focused on refactoring. It seems as though it's working now, so I'll have a look through it one more time, but assuming all is well I'll go ahead and merge.

2025-02-24 03:03 UTC, ian612 approved these changes

2025-02-24 03:05 UTC, ian612 approved these changes
I can find no further issues with anything after some more testing, so I'm going to approve and merge this. Again, thanks a ton for taking a go at this, you've done a really nice job slimming and streamlining it down.

2025-02-24 03:06 UTC, merged