Envoy Improvizations from Armory and updates to modern attributes
foundryvtt-starfinder/foundryvtt-starfinder pull request #1418
Opened 2024-12-25 02:18 UTC by rmorgens

Adds missing Armory Envoy Improvizations as well as updating attributes to modern aspects

Replaces PR#1229

2024-12-25 02:22 UTC, rmorgens commented
Addresses Issue #940 
Addresses Issue #1062

2025-01-23 02:15 UTC, ian612 requested changes
I've merged the latest changes into this branch and resolved the conflicts. There seem to be some issues with incorrectly formatted links. If you run `cook` it will show a list of the files that need fixing (you can ignore the error that shows up in `operative_exploit.json`).

2025-01-27 00:54 UTC, rmorgens commented
Links should be updated.  Cook issues were missing '.Item' on Class-Features and Conditions links from pre-update build

2025-01-29 02:17 UTC, ian612 approved these changes

2025-01-29 02:17 UTC, merged