Adding missing Soldier styles, mostly from APs and cleanup of Spellbrawler
foundryvtt-starfinder/foundryvtt-starfinder pull request #1419
Opened 2024-12-26 05:25 UTC by rmorgens

Adds Commander, Gloom Gunner, Pistol Dancer and Silent Slayer.  Updates to Spellbrawler, along with some new effects including a touch on Coordinated Shot to link in its new effect

2024-12-26 05:25 UTC, rmorgens commented
Addresses Issue#1041

2025-01-20 16:15 UTC, ian612 reviewed
This needs a few changes, the Silent Slayer style and features look to be duplicated, it's better to just edit the existing features. In addition, `npm run cook` throws some errors regarding broken links which need to be fixed.

2025-01-20 16:15 UTC, ian612 commented on src/items/class-features/claws_of_the_shadow_(ex).json
> +  "_id": "bt78rrYyxhIKU9oo",
Rather than creating a new item, make any edits to the existing claws of the shadow item. This will keep IDs the same and make sure links aren't broken

2025-01-20 16:15 UTC, ian612 commented on src/items/class-features/darting_shadow_(ex).json
> +  "_id": "z1yV6QIBL9jbtDd9",
Same comment as Claws of the Shadow

2025-01-20 16:15 UTC, ian612 commented on src/items/class-features/fading_shadow_(su).json
> +  "_id": "OnWlMx4eRv0Mvm7V",
Same comment as Claws of the Shadow

2025-01-20 16:15 UTC, ian612 commented on src/items/class-features/fighting_style.json
> +      "value": "<p>&gt;@UUID[Compendium.sfrpg.classes.Item.cCZQpV0NmYE9qZoL]{Soldier}</p>\n<p>You have a preferred fighting style that represents the type of soldier you are. Each fighting style is c
Make sure that this link references the original Silent Slayer feature id

2025-01-20 16:15 UTC, ian612 commented on src/items/class-features/severing_shadow_(ex).json
> +  "_id": "98xqS2frRuIZFapt",
Same comment as Claws of the Shadow

2025-01-20 16:15 UTC, ian612 commented on src/items/class-features/weeping_shadow_(ex).json
> +  "_id": "9sGXf7cixdNCUnL8",
Same comment as Claws of the Shadow

2025-01-20 16:15 UTC, ian612 commented on src/items/class-features/silent_slayer.json
> +  "_id": "mSpFz2mpi87u063p",
Silent Slayer is already in the system, so it's better to edit the existing feature and its sub-features to keep the IDs the same. This will prevent broken links

2025-01-20 16:16 UTC, ian612 requested changes
See comments above

2025-01-26 23:13 UTC, rmorgens commented
Tried to fix things.  The deletions didn't seem to commit.  I manually deleted the extraneous spell_brawler.json, but the 5 features associated with Silent Slayer were renamed and not sure that is showing.  Cook is still seeing those files which are causing most of the issues.  (If the features has (1st), (2nd), etc in the name, they should be deleted.....
Claws of the Shadow (Ex) - 1st Level
Darting Shadow (Su) - 5th Level
Fading Shadow (Su) - 9th Level
Severing Shadow (Ex) - 13th Level
Weeping Shadow (Ex) - 17th Level

Not sure what is going on with Cook seeing an issue with Operative Exploit, which this shouldn't have touched....

2025-01-26 23:15 UTC, rmorgens commented on src/items/class-features/silent_slayer.json
> +  "_id": "mSpFz2mpi87u063p",
Yeah, didn't see the dup, and the non-std implementation caused me to miss it on my original faulty validation.

2025-01-28 20:30 UTC, ian612 approved these changes

2025-01-28 20:30 UTC, merged