Skill Expertise Update
foundryvtt-starfinder/foundryvtt-starfinder pull request #835
Opened 2022-12-03 04:34 UTC by Iankid

-Updated skill expertise related items with modifiers, and making them active feats for forgoing skill expertise.
-Added missing Expert Advice (Ex) item.
Fixes #834

2022-12-04 13:16 UTC, LebombJames requested changes

2022-12-04 13:16 UTC, LebombJames commented on src/items/class-features/additional_skill_expertise_(ex).json
> +        "modifierType": "constant",
These need to be situational in order for the dice to work correctly. Additionally, if they're situational you don't need to make it an active feat, you can just turn it off when needed

2022-12-07 21:21 UTC, Iankid commented
This PR awaiting "Null" option in skill modifiers for better user interface.

2023-06-15 13:02 UTC, LebombJames commented on src/items/class-features/hunter’s_expertise_(ex)_(1st).json
> +        "notes": "You gain a free skill rank at each soldier level, from 9th onward, you can use only for Perception or Survival (this does not allow you to exceed the maximum number of skill ranks i
```suggestion
        "notes": "If you take the hunter fighting style as your secondary fighting style, from 9th onward you gain a free skill rank at each soldier level you can use only for Perception or Survival (this does not allow you to exceed the maximum number of skill ranks in a single skill).",

2023-06-15 13:17 UTC, merged