Adding missing Operative Exploits - mostly Armory
foundryvtt-starfinder/foundryvtt-starfinder pull request #996
Opened 2023-03-04 20:08 UTC by rmorgens

Adding missing Operative Exploits, mostly from Armory

2023-03-04 20:09 UTC, rmorgens commented
Addresses Issue#859 Trap Spotter Missing

2023-03-22 14:45 UTC, LebombJames commented on src/items/class-features/concealed_weaponry_(ex).json
> +        "modifier": "round((@classes.operative.levels + 3) / 4) * 2",
Use the updated operative's edge formula

2023-03-22 14:46 UTC, LebombJames commented on src/items/class-features/concealed_weaponry_(ex).json
> +        "notes": "bonus to Sleight of Hand checks when attempting to hide a small object on your body.",
Include the "Double your operative's edge bonus..." here

2023-03-22 14:48 UTC, LebombJames commented on src/items/class-features/disarming_attack_(ex).json
> +      "type": "",
Add the reflex save

2023-03-22 14:51 UTC, LebombJames commented on src/items/class-features/knee_shot_(ex).json
> +      "type": "",
Add the reflex save

2023-03-22 14:53 UTC, LebombJames commented on src/items/class-features/surveillance_wraith_(ex).json
> +      "value": "<p>&gt;@UUID[Compendium.sfrpg.class-features.On2ZrPJTe8FURsXY]{Operative Exploit}</p>\n<p>You are invisible to technological surveillance systems and most forms of divination magic, p
Link to non-detection, and italicise it

2023-03-22 14:53 UTC, LebombJames commented on src/items/class-features/trap_spotter_(ex).json
> +        "modifier": "round((@classes.operative.levels + 3) / 4) * 2",
Same notes as concealed weapon

2023-03-22 14:54 UTC, LebombJames requested changes
.

2023-03-26 14:09 UTC, LebombJames commented
If you're updating details, remember to set these (and ones from other PRs) as class features

2023-04-04 20:56 UTC, LebombJames requested changes
Just take another look over and ensure you're not including links/checks when they're not necessary (and to ensure you're using skill checks on the details tab too)

2023-04-04 20:56 UTC, LebombJames commented on src/items/class-features/daring_explorer_(ex).json
> +      "value": "<p>&gt;@UUID[Compendium.sfrpg.class-features.On2ZrPJTe8FURsXY]{Operative Exploit}</p>\n<p>When you fail an @Check[type:acrobatics] or @Check[type:athletics], you can spend 1 Resolve P
I recommend going over these again and ensuring `@Check` is only used when the ability calls for a check (from you or an enemy), not when it is simply talking about a skill/save/etc

2023-04-04 20:56 UTC, LebombJames commented on src/items/class-features/elite_saboteur_(ex).json
> +      "value": "<p>&gt;@UUID[Compendium.sfrpg.class-features.On2ZrPJTe8FURsXY]{Operative Exploit}</p>\n<p>You can attempt an @Check[type:engineering] to disable a device on a lock or trap in half the
For things like this, you should add a Skill Check in the details tab so it appears on the chat card

2023-04-04 20:56 UTC, LebombJames commented on src/items/class-features/feign_death_(ex).json
> +      "value": "<p>&gt;@UUID[Compendium.sfrpg.class-features.On2ZrPJTe8FURsXY]{Operative Exploit}</p>\n<p>Whenever you take damage, you can attempt to feign death as a reaction. You immediately fall
This is another example of something that needs a Skill Check

2024-12-22 17:52 UTC, rmorgens commented
Replaced by PR#1412

2024-12-22 17:52 UTC, closed without merging